version: "3.9"
services:
  test:
    build:
      context: .
      args:
        SDL3_VERSION: 3.2.12
        SDL3_IMAGE_VERSION: 3.2.4
        SDL3_TTF_VERSION: 3.2.2
    volumes:
      - ./bin:/app/bin
      - ./examples:/app/examples
      - ./fonts:/app/fonts
      - ./images:/app/images
      - ./include:/app/include
      - ./src:/app/src
      - ./tests:/app/tests
    tty: true
