name: Build

on:
  push:
    branches:
      - main
    paths:
      - include/**
      - tests/**
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - main
  workflow_dispatch:
    inputs:
      SDL3_VERSION:
        description: "SDL3 version"
        required: false
        default: "3.2.12"
      SDL3_IMAGE_VERSION:
        description: "SDL3_image version"
        required: false
        default: "3.2.4"
      SDL3_TTF_VERSION:
        description: "SDL3_ttf version"
        required: false
        default: "3.2.2"

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install SDL dependencies
        uses: HandcrankEngine/install-sdl-packages@v0.1.2
        with:
          SDL3_VERSION: ${{ inputs.SDL3_VERSION || '3.2.12' }}
          SDL3_IMAGE_VERSION: ${{ inputs.SDL3_IMAGE_VERSION || '3.2.4' }}
          SDL3_TTF_VERSION: ${{ inputs.SDL3_TTF_VERSION || '3.2.2' }}

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake

      - name: Build and test
        run: |
          cmake .github/workflows/
          make
