name: Build

on:
  push:
    branches:
      - main
    paths:
      - include/**
      - tests/**
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - main
  workflow_dispatch:
    inputs:
      SDL_VERSION:
        description: "SDL version"
        required: false
        default: "3.4.10"
      SDL_IMAGE_VERSION:
        description: "SDL_image version"
        required: false
        default: "3.4.4"
      SDL_TTF_VERSION:
        description: "SDL_ttf version"
        required: false
        default: "3.2.2"
      SDL_MIXER_VERSION:
        description: "SDL_mixer version"
        required: false
        default: "3.2.4"

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false

    strategy:
      matrix:
        include:
          - SDL_VERSION: 3.4.10
            SDL_IMAGE_VERSION: 3.4.4
            SDL_TTF_VERSION: 3.2.2
            SDL_MIXER_VERSION: 3.2.4

    steps:
      - name: Check out repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install SDL dependencies
        uses: HandcrankEngine/install-sdl-packages@3dd8adf2ce1e6698313aecb05a2f8fa59be27b8c # v0.4.1
        with:
          SDL_VERSION: ${{ inputs.SDL_VERSION || matrix.SDL_VERSION }}
          SDL_IMAGE_VERSION: ${{ inputs.SDL_IMAGE_VERSION || matrix.SDL_IMAGE_VERSION }}
          SDL_TTF_VERSION: ${{ inputs.SDL_TTF_VERSION || matrix.SDL_TTF_VERSION }}
          SDL_MIXER_VERSION: ${{ inputs.SDL_MIXER_VERSION || matrix.SDL_MIXER_VERSION }}

      - name: Build and test
        working-directory: .github/workflows/
        run: |
          mkdir build
          (cd build/ && cmake ..)
          (cd build/ && cmake --build .)
