name: Tests

on:
  push:
    branches:
      - main
    paths:
      - include/**
      - tests/**
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - main
  workflow_dispatch:
    inputs:
      SDL_VERSION:
        description: "SDL version"
        required: false
        default: "3.2.22"
      SDL_IMAGE_VERSION:
        description: "SDL_image version"
        required: false
        default: "3.2.4"
      SDL_TTF_VERSION:
        description: "SDL_ttf version"
        required: false
        default: "3.2.2"
      SDL_MIXER_VERSION:
        description: "SDL_mixer version"
        required: false
        default: "2.8.1"

jobs:
  tests:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install SDL dependencies
        uses: HandcrankEngine/install-sdl-packages@v0.3.0
        with:
          SDL_VERSION: ${{ inputs.SDL_VERSION || '3.2.22' }}
          SDL_IMAGE_VERSION: ${{ inputs.SDL_IMAGE_VERSION || '3.2.4' }}
          SDL_TTF_VERSION: ${{ inputs.SDL_TTF_VERSION || '3.2.2' }}
          SDL_MIXER_VERSION: ${{ inputs.SDL_MIXER_VERSION || '2.8.1' }}

      - name: Run tests
        run: ./bin/run-tests.sh
