name: Tests

on:
  push:
    branches:
      - main
    paths:
      - include/**
      - tests/**
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - main
  workflow_dispatch:
    inputs:
      SDL2_VERSION:
        description: "SDL2 version"
        required: false
        default: "2.32.6"
      SDL2_IMAGE_VERSION:
        description: "SDL2_image version"
        required: false
        default: "2.8.8"
      SDL2_TTF_VERSION:
        description: "SDL2_ttf version"
        required: false
        default: "2.24.0"
      SDL2_MIXER_VERSION:
        description: "SDL2_mixer version"
        required: false
        default: "2.8.1"

jobs:
  tests:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install SDL dependencies
        uses: HandcrankEngine/install-sdl-packages@v0.2.0
        with:
          SDL2_VERSION: ${{ inputs.SDL2_VERSION || '2.32.6' }}
          SDL2_IMAGE_VERSION: ${{ inputs.SDL2_IMAGE_VERSION || '2.8.8' }}
          SDL2_TTF_VERSION: ${{ inputs.SDL2_TTF_VERSION || '2.24.0' }}
          SDL2_MIXER_VERSION: ${{ inputs.SDL2_MIXER_VERSION || '2.8.1' }}

      - name: Run tests
        run: ./bin/run-tests.sh
